### ISSUE TITLE
conv version resolve fails

### ISSUE THREAD

**Issue by jslll135** [jedisct1/dnssector#20]
[chomp uses std feature](https://github.com/m4rw3r/chomp/blob/31795bdabc183677db8d857fdc842d14eb541fb7/Cargo.toml#L27) of conv which does not exist in [0.3.3](https://github.com/DanielKeep/rust-conv/blob/c7ce0c3beca06211234467faf800def13786dc28/Cargo.toml).  Somehow only build in nixos's sandbox is affect (maybe related to --offline and --frozen, not sure). Since conv and chomp are not maintained for several years, I reports here instead. Could you please fix it? Thanks!

See also https://github.com/NixOS/nixpkgs/pull/169326#discussion_r860725815

**Comment by jedisct1** [comment]
Do you know how to fix this?

**Comment by jedisct1** [comment]
`dnssector` was updated with a fork of `chomp`.

**Comment by jslll135** [comment]
Thanks!
